name: cricbook
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  http: ^1.3.0
  intl: ^0.20.2
  shimmer: ^3.0.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  connectivity_plus: ^6.1.4
  sqflite: ^2.4.1
  path: ^1.9.0
  pdf: ^3.6.0
  printing: ^5.10.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/vectors/cricket.png
